### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by psypherium**
markup and more info

### CODE REVIEW

**Comment by psypherium** [comment]
Sorry it is a little messy. The aim is to make it cleaner in the long run. Readme.md and other such things can be kept in the .github folder and still function normally.

**Comment by psypherium** [comment]
the link to the picture would need to be changed after the push is merged, since the file would then exist in the main repo instead of inside "patch-1"

**Comment by JustusAvramenko** [comment]
Looks nicer than before, definitely. I think the screenshot should be updated for the Suebians, since they now have their own building set.

**Comment by psypherium** [comment]
I don't have a great screenshhot of new Suebians yet, I need to play them again on a nicer map, and make a bigger town.

**Comment by psypherium** [comment]
delenda_est_logo
 Is there a version of this without the blood or background? It would be good for a hheader to thhe README, but to be honest I'm mainly looking for it so I can easily make youtube thumbnails, haha.

**Pull request merged**
